### ISSUE TITLE
Update of HostedZone fails

### ISSUE THREAD

**Issue by sibezza** [widdix/mastodon-on-aws#39]
Initial CF stack deployment completed successfully, following the instructions in your README. We initially attached Route53 to a subdomain of an existing TLD while we appraised Mastodon itself. We now want to move it to its own TLD, and attempted to do so by updating the stack using the existing template, and just changing the domain name. The nested stack 'mastodon-on-aws-HostedZone' update failed with the following error:
`Export mastodon-on-aws-HostedZone-JBF4DGI244BG-Id cannot be updated as it is in use by mastodon-on-aws-Certificate-5JU2DVO0L8TX and mastodon-on-aws-Record-11NDK0SP12680`

**Comment by michaelwittig** [comment]
Hi @sibezza Changing the `DomainName` is not possible out of the box. What you could do (without loosing data) is this:

1. Open the CloudFormation template (`mastodon.yml`) in an text editor, uncomment the following resources:

Example:
 
```yaml
Resources:
  Secret:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      # [...]
#  HostedZone:
#    Type: 'AWS::CloudFormation::Stack'
#    Properties:
#      Parameters:
#        Name: !Ref DomainName
#      TemplateURL: './node_modules/@cfn-modules/route53-hosted-zone-public/module.yml'
```

* `HostedZone`
* `Certificate`
* `AlbListener`
* `Target`
* `WebService`
* `StreamingApiTarget`
* `StreamingApiService`
* `Record`
* `Dkim1Record`
* `Dkim2Record`
* `Dkim3Record`

3. Update the stack with the new `DomainName` parameter and the modified template. Wait for the update to finish.

4. Revert the changes to the template and update the stack with the original template. Wait for the update to finish.
